---
title: 德國旅遊互動地圖
email: your-email@example.com
description: >-
  探索德國 16 邦的在地景點與城市。
baseurl: "/adventure_in_de" # 如果是個人主頁則留空 ""
url: "https://joedventure.github.io"

permalink: /:categories/:title/

# 集合設定 (針對底線資料夾)
collections:
  bundesland:
    output: true
    
markdown: kramdown
theme: minima # 或自定義主題

# 廣告設定預留
#google_adsense_client: "ca-pub-xxxxxxxxxxxx"
